version: '3'

networks:
  db:
  workers:

services:
  dbMailServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: P@ssword42
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - db
    # mem_limit: 1G
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - workers
    # mem_limit: 250M
  api:
    image: sendmai.api.11
    build: backend/MailSender.Api
    volumes:
      - ./settings/appsettings.json:/app/appsettings.json
    ports:
      - 8080:80
    depends_on:
      - dbMailServer
      - rabbitmq
    networks:
      - db
      - workers
  worker:
    image: sendmail.worker.11
    volumes:
      - ./settings/appsettings.json:/app/appsettings.json
    build: worker/MailSender.Worker
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - workers
