version: '2.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: P@ssword42
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    mem_limit: 2G