version: '2.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: P@ssword42
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    mem_limit: 1G
  queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - 15672:15672
      - 5672:5672
    mem_limit: 250M
  api:
    image: sendmailapi
    build: backend/MailSender.Api
    ports:
      - 5001:5001
      - 5002:5002
    depends_on:
      - db
